print("Welcome to love calculator!")
name1=input("Enter First name : ")
name2=input("Enter Second name : ")
main_name=name1+name2
main_name=main_name.lower()

t=main_name.count("t")
r=main_name.count("r")
u=main_name.count("u")
e=main_name.count("e")
first_digit=str(t+r+u+e)
l=main_name.count("l")
o=main_name.count("o")
v=main_name.count("v")
e=main_name.count("e")
second_dight=str(l+o+v+e)
soure=int(first_digit+second_dight)
print(f"Your scoure is {soure}")